[project]
name = "fishmlserv"
version = "0.4.0"
description = "Creating a ML model -usingsklartn(KNeighborsClassifier"
authors = [
    {name = "S00zzang", email = "sujinpark8719561@gmail.com"},
]
dependencies = [
    "fishmlserv @ file:///${PROJECT_ROOT}/",
    "uvicorn[standard]>=0.30.6",
    "fastapi>=0.112.2",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
